import type { Metadata } from "next";
import "./globals.css";
import TopNavbar from "@/components/TopNavbar";
import 'boxicons/css/boxicons.min.css';
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`xs:bg-white xs:text-black overflow-x-hidden antialiased`}
      >
        <TopNavbar />
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
